name: Train Model via MLflow Project and Push Docker Image

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: 3.12
        environment-file: MLProject/conda.yaml
        activate-environment: co2-env

    - name: Install MLflow (again, to be sure)
      run: pip install mlflow

    - name: Run MLflow Project
      run: |
        cd MLProject
        mlflow run . --no-conda

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: MLProject/mlruns/

    - name: Build Docker Image
      run: |
        cd MLProject
        RUN_ID=$(ls mlruns/0 | head -n 1)
        mlflow models build-docker -m mlruns/0/$RUN_ID/artifacts/model -n co2-image

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker Image
      run: |
        docker tag co2-image:latest ${{ secrets.DOCKERHUB_USERNAME }}/co2-image:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/co2-image:latest
