name: CO2 Emission Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[AUTO]')"  # Prevent self-trigger loop
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Disable default GitHub token for push
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow 
          pip install seaborn
      - name: Run mlflow project
        run: |
          mlflow run MLProject --env-manager=local
      - name: Archive MLflow artifacts locally
        run: |
          mkdir -p saved-artifacts
          cp -r mlruns saved-artifacts/
      - name: Commit and push changes
        env:
          TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "Automated Preprocessor"
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
          git fetch origin
          git pull origin main
          git add saved-artifacts/
          git diff --cached --quiet || git commit -m "[AUTO] Add trained model artifacts from CI run"
          git push origin main
      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"
      - name: Build Docker Model
        run: |
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "cc"
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Docker Image
        run: |
          docker tag cc ${{ secrets.DOCKER_HUB_USERNAME }}/co2-emissions:latest
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/co2-emissions:latest

